"""
Real Indian bank home loan data — sourced from Paisabazaar, GoodReturns,
Business Standard (Jan–Feb 2026). For DEMO use only; verify before production.
RBI Repo Rate as of Feb 2026: 5.25%
"""

BANKS = [
    {
        "id": "sbi",
        "name": "State Bank of India",
        "short_name": "SBI",
        "type": "public",
        "logo": "🏦",
        "rate_min": 7.25,
        "rate_max": 8.70,
        "rate_type": "floating",   # RLLR-linked
        "benchmark": "RLLR",
        "min_loan_amount": 500000,     # ₹5 Lakh
        "max_loan_amount": 75000000,   # ₹7.5 Crore
        "min_tenure_years": 5,
        "max_tenure_years": 30,
        "processing_fee_pct": 0.35,    # 0.35% of loan amount
        "processing_fee_min": 2000,
        "processing_fee_max": 10000,   # capped at ₹10,000 for loans > ₹75L
        "processing_fee_note": "0.35% (min ₹2,000, max ₹10,000). Waived in festive schemes.",
        "prepayment_floating": 0.0,    # Nil for floating rate (RBI mandated)
        "prepayment_fixed": 0.0,       # SBI charges nil even on fixed
        "foreclosure_floating": 0.0,
        "foreclosure_fixed": 0.0,
        "min_cibil": 650,
        "max_ltv": 90,                 # up to 90% for loans < ₹30L
        "min_age": 18,
        "max_age": 70,
        "special_features": [
            "No prepayment penalty on floating rate",
            "PMAY subsidy eligible",
            "Special rate for women borrowers",
            "SBI MaxGain (OD facility) available",
        ],
        "womens_concession": 0.05,     # 5 bps concession for women
        "cibil_slabs": [
            {"min": 750, "max": 900, "rate": 7.25},
            {"min": 700, "max": 749, "rate": 7.75},
            {"min": 650, "max": 699, "rate": 8.25},
            {"min": 0,   "max": 649, "rate": 8.70},
        ],
    },
    {
        "id": "hdfc",
        "name": "HDFC Bank",
        "short_name": "HDFC",
        "type": "private",
        "logo": "🏛️",
        "rate_min": 7.20,
        "rate_max": 13.20,
        "rate_type": "floating",
        "benchmark": "RLLR",
        "min_loan_amount": 1500000,
        "max_loan_amount": 100000000,
        "min_tenure_years": 5,
        "max_tenure_years": 30,
        "processing_fee_pct": 0.50,
        "processing_fee_min": 10000,
        "processing_fee_max": 45000,
        "processing_fee_note": "Up to 0.50% or ₹10,000 whichever is higher (max ₹45,000). Festive waivers available.",
        "prepayment_floating": 0.0,
        "prepayment_fixed": 2.0,       # 2% on fixed rate loans
        "foreclosure_floating": 0.0,
        "foreclosure_fixed": 2.0,
        "min_cibil": 700,
        "max_ltv": 90,
        "min_age": 21,
        "max_age": 65,
        "special_features": [
            "Smart Fix - part fixed part floating",
            "Home Loan Balance Transfer facility",
            "Step-up EMI for early career borrowers",
            "Digital doorstep service",
        ],
        "womens_concession": 0.05,
        "cibil_slabs": [
            {"min": 800, "max": 900, "rate": 7.20},
            {"min": 750, "max": 799, "rate": 7.70},
            {"min": 700, "max": 749, "rate": 8.20},
            {"min": 0,   "max": 699, "rate": 8.70},
        ],
    },
    {
        "id": "icici",
        "name": "ICICI Bank",
        "short_name": "ICICI",
        "type": "private",
        "logo": "🏢",
        "rate_min": 7.65,
        "rate_max": 9.80,
        "rate_type": "floating",
        "benchmark": "RLLR",
        "min_loan_amount": 1500000,
        "max_loan_amount": 100000000,
        "min_tenure_years": 5,
        "max_tenure_years": 30,
        "processing_fee_pct": 0.30,
        "processing_fee_min": 10000,
        "processing_fee_max": 50000,
        "processing_fee_note": "Up to 0.30% of loan amount (max ₹50,000) + GST",
        "prepayment_floating": 0.0,    # Nil per RBI guidelines
        "prepayment_fixed": 2.0,
        "foreclosure_floating": 0.0,
        "foreclosure_fixed": 2.0,
        "min_cibil": 700,
        "max_ltv": 90,
        "min_age": 21,
        "max_age": 65,
        "special_features": [
            "No prepayment penalty on floating rate",
            "ICICI Home Loan Overdraft facility",
            "Pre-approved loans for existing customers",
            "PMAY linked",
        ],
        "womens_concession": 0.05,
        "cibil_slabs": [
            {"min": 800, "max": 900, "rate": 7.65},
            {"min": 750, "max": 799, "rate": 8.00},
            {"min": 700, "max": 749, "rate": 8.50},
            {"min": 0,   "max": 699, "rate": 9.00},
        ],
    },
    {
        "id": "axis",
        "name": "Axis Bank",
        "short_name": "Axis",
        "type": "private",
        "logo": "🏗️",
        "rate_min": 7.60,
        "rate_max": 9.40,
        "rate_type": "floating",
        "benchmark": "RLLR",
        "min_loan_amount": 500000,
        "max_loan_amount": 50000000,
        "min_tenure_years": 5,
        "max_tenure_years": 30,
        "processing_fee_pct": 1.00,
        "processing_fee_min": 10000,
        "processing_fee_max": 75000,
        "processing_fee_note": "Up to 1% of loan amount (max ₹75,000) + GST",
        "prepayment_floating": 0.0,
        "prepayment_fixed": 2.0,
        "foreclosure_floating": 0.0,
        "foreclosure_fixed": 2.0,
        "min_cibil": 700,
        "max_ltv": 85,
        "min_age": 21,
        "max_age": 65,
        "special_features": [
            "Shubh Aarambh Home Loan - no EMI for 3 months",
            "Fast Forward - bi-monthly EMI option",
            "Asha Home Loan for informal income borrowers",
        ],
        "womens_concession": 0.05,
        "cibil_slabs": [
            {"min": 800, "max": 900, "rate": 7.60},
            {"min": 750, "max": 799, "rate": 8.00},
            {"min": 700, "max": 749, "rate": 8.60},
            {"min": 0,   "max": 699, "rate": 9.00},
        ],
    },
    {
        "id": "pnb",
        "name": "Punjab National Bank",
        "short_name": "PNB",
        "type": "public",
        "logo": "🏦",
        "rate_min": 7.20,
        "rate_max": 10.00,
        "rate_type": "floating",
        "benchmark": "RLLR",
        "min_loan_amount": 500000,
        "max_loan_amount": 50000000,
        "min_tenure_years": 5,
        "max_tenure_years": 30,
        "processing_fee_pct": 0.35,
        "processing_fee_min": 2500,
        "processing_fee_max": 15000,
        "processing_fee_note": "0.35% (min ₹2,500, max ₹15,000) + GST. Occasional festive waivers.",
        "prepayment_floating": 0.0,
        "prepayment_fixed": 2.0,
        "foreclosure_floating": 0.0,
        "foreclosure_fixed": 2.0,
        "min_cibil": 650,
        "max_ltv": 90,
        "min_age": 18,
        "max_age": 70,
        "special_features": [
            "PNB Pride for government employees",
            "PNB Max Saver OD account",
            "No prepayment on floating",
            "PMAY eligible",
        ],
        "womens_concession": 0.05,
        "cibil_slabs": [
            {"min": 750, "max": 900, "rate": 7.20},
            {"min": 700, "max": 749, "rate": 7.70},
            {"min": 650, "max": 699, "rate": 8.30},
            {"min": 0,   "max": 649, "rate": 9.00},
        ],
    },
    {
        "id": "bob",
        "name": "Bank of Baroda",
        "short_name": "BoB",
        "type": "public",
        "logo": "🏦",
        "rate_min": 7.45,
        "rate_max": 9.95,
        "rate_type": "floating",
        "benchmark": "RLLR",
        "min_loan_amount": 500000,
        "max_loan_amount": 100000000,
        "min_tenure_years": 5,
        "max_tenure_years": 30,
        "processing_fee_pct": 0.50,
        "processing_fee_min": 8500,
        "processing_fee_max": 25000,
        "processing_fee_note": "0.50% (min ₹8,500, max ₹25,000) + GST",
        "prepayment_floating": 0.0,
        "prepayment_fixed": 2.0,
        "foreclosure_floating": 0.0,
        "foreclosure_fixed": 2.0,
        "min_cibil": 675,
        "max_ltv": 90,
        "min_age": 21,
        "max_age": 70,
        "special_features": [
            "Baroda Home Loan Advantage",
            "Baroda CRE Home Loan for commercial RE",
            "Top-up loan facility",
        ],
        "womens_concession": 0.05,
        "cibil_slabs": [
            {"min": 750, "max": 900, "rate": 7.45},
            {"min": 700, "max": 749, "rate": 7.95},
            {"min": 675, "max": 699, "rate": 8.45},
            {"min": 0,   "max": 674, "rate": 9.00},
        ],
    },
    {
        "id": "kotak",
        "name": "Kotak Mahindra Bank",
        "short_name": "Kotak",
        "type": "private",
        "logo": "🏢",
        "rate_min": 7.99,
        "rate_max": 9.50,
        "rate_type": "floating",
        "benchmark": "RLLR",
        "min_loan_amount": 1500000,
        "max_loan_amount": 50000000,
        "min_tenure_years": 5,
        "max_tenure_years": 20,
        "processing_fee_pct": 0.50,
        "processing_fee_min": 10000,
        "processing_fee_max": 50000,
        "processing_fee_note": "0.50% + GST (max ₹50,000)",
        "prepayment_floating": 0.0,
        "prepayment_fixed": 2.0,
        "foreclosure_floating": 0.0,
        "foreclosure_fixed": 2.0,
        "min_cibil": 720,
        "max_ltv": 85,
        "min_age": 21,
        "max_age": 60,
        "special_features": [
            "Digital approval in 10 minutes",
            "Balance transfer with top-up",
            "Kotak Home First for first-time buyers",
        ],
        "womens_concession": 0.05,
        "cibil_slabs": [
            {"min": 800, "max": 900, "rate": 7.99},
            {"min": 750, "max": 799, "rate": 8.40},
            {"min": 720, "max": 749, "rate": 8.90},
            {"min": 0,   "max": 719, "rate": 9.50},
        ],
    },
    {
        "id": "lichousing",
        "name": "LIC Housing Finance",
        "short_name": "LIC HFL",
        "type": "hfc",
        "logo": "🏠",
        "rate_min": 7.50,
        "rate_max": 10.50,
        "rate_type": "floating",
        "benchmark": "PLR",
        "min_loan_amount": 500000,
        "max_loan_amount": 75000000,
        "min_tenure_years": 5,
        "max_tenure_years": 30,
        "processing_fee_pct": 0.50,
        "processing_fee_min": 10000,
        "processing_fee_max": 15000,
        "processing_fee_note": "0.50% (max ₹15,000) + GST",
        "prepayment_floating": 0.0,
        "prepayment_fixed": 2.0,
        "foreclosure_floating": 0.0,
        "foreclosure_fixed": 2.0,
        "min_cibil": 650,
        "max_ltv": 90,
        "min_age": 21,
        "max_age": 60,
        "special_features": [
            "LIC Griha Varishtha for senior citizens",
            "Plot + construction loan",
            "NRI home loans",
            "Home renovation loans",
        ],
        "womens_concession": 0.10,
        "cibil_slabs": [
            {"min": 750, "max": 900, "rate": 7.50},
            {"min": 700, "max": 749, "rate": 8.00},
            {"min": 650, "max": 699, "rate": 8.70},
            {"min": 0,   "max": 649, "rate": 9.50},
        ],
    },
]
